### ISSUE TITLE
Dudas al realizar los tests en Fundamentos de JavaScript I @pedroprieto

### ISSUE THREAD

**Issue by josepercas** [josepercas/practica_dwec_gestor_presupuesto#1]
@pedroprieto Hola Pedro. He realizado esta parte de la práctica pero me da errores tanto al ejecutar **npm install**, y luego al realizar los **_tests_** me saltan errores que no sé si se deben a los fallos de **npm instal**l o a que mi código realmente está mal. Está subido lo que tengo realizado. Te he adjuntado el Word "_Errores_Fundamentos.de.JavaScript.I.docx_" con el resultado que me da al pasar el **test1**

Muchas gracias y un saludo.
[Errores_Fundamentos de JavaScript I.docx](https://github.com/josepercas/practica_dwec_gestor_presupuesto/files/13199132/Errores_Fundamentos.de.JavaScript.I.docx)

**Comment by pedroprieto** [comment]
Buenas,

Como te he comentado en el foro, lo de `npm install` no tiene importancia: los tests se ejecutan con normalidad.

Efectivamente, tu código no está bien. Por ejemplo, no compruebas si se pasa un número correcto: solo compruebas si se pasa un número menor que 0. Pero, ¿qué ocurre si se pasa una cadena de texto? En ese caso, la función debería almacenar 0.
https://github.com/josepercas/practica_dwec_gestor_presupuesto/blob/816153abbf286eed1b94b519c708fa5649673533/js/gestionPresupuesto.js#L9

Un saludo!

**Comment by pedroprieto** [comment]
Por cierto, acuérdate de activar las `Actions` en la pestaña de tu repositorio.

**Comment by josepercas** [comment]
@pedroprieto. He activado. las Actions y con la pista que me has dado he conseguido reducir los fallos a uno. Pero este último no termino de ver porque falla. Me dice lo siguiente:

  1) Función CrearGasto y funcionamiento de objeto gasto
       Método 'actualizarValor' del objeto gasto:

      AssertionError: expected 0 to equal 100.58
      + expected - actual

      -0
      +100.58
      
      at Context.<anonymous> (file:///C:/Jose/DAW/DWEC/Practica_DWEC/practica_dwec_gestor_presupuesto/test/01_testIntroJSI.js:102:16)
      at process.processImmediate (node:internal/timers:478:21)
      at process.callbackTrampoline (node:internal/async_hooks:130:17)

He revisado el código y no sé donde puedo estar fallando esta vez. 
Gracias!!

**Comment by pedroprieto** [comment]
Buenas,

El enunciado dice lo siguiente:
![imagen](https://github.com/josepercas/practica_dwec_gestor_presupuesto/assets/7632447/a5dda17c-9f69-41ab-9517-16f4dc296dab)

Y tú lo pones a 0:
https://github.com/josepercas/practica_dwec_gestor_presupuesto/blob/e90690310b00a1511c13eeb0728f34d53a6d31df/js/gestionPresupuesto.js#L44

Un saludo!

**Comment by josepercas** [comment]
Tengo que mejorar mi lectura comprensiva.... madre mía... lo he leído mil veces y viéndolo ahora con lo que me remarcas lo entiendo. Ahora si funciona. Subo ya el código modificado.

Muchas gracias por todo. :)
