### ISSUE TITLE
No entiendo que estoy haciendo mal para que me de error al importar los módulos

### ISSUE THREAD

**Issue by josepercas** [josepercas/practica_dwec_gestor_presupuesto#2]
@pedroprieto. Hola Pedro, no sé que estoy haciendo mal con el tema de importar módulos, pero algo no estoy haciendo bien y no doy con ello. Si miras el archivo "interaccionHTML.html" verás que estoy importando el módulo "generarDatosEstaticos.js" que está en la carpeta "js" y a su vez en "generarDatosEstaticos.js" importo los módulos "gestionPresupuestoWeb.js" y "gestionPresupuesto.js", que están en la misma ruta que "generarDatosEstaticos.js", dentro de "js". Estoy poniendo type = "module" pero no hay forma, me devuelve constantemente el fallo: 

interaccionHTML.html:1 Uncaught TypeError: Failed to resolve module specifier "chai". Relative references must start with either "/", "./", or "../".

Muchas gracias y un saludo.

**Comment by josepercas** [comment]
Me he dado cuenta que estaba, al principio del fichero 'gestionPresupuesto.js', la línea _import {assert} from "chai";_. La he comentado y ya ha funcionado. Lo que no sé es si la línea la pegué yo ahí por error (no sé ni como) o si ya estaba y será necesaria para el avance de la práctica.

Gracias.

**Comment by pedroprieto** [comment]
Buenas,

Sí, esa línea no va ahí: es de los test. Se ve que la copiaste por error.

Un saludo!!
