### ISSUE TITLE
@pedroprieto Problemas en la práctica "Eventos en JavaScript"

### ISSUE THREAD

**Issue by josepercas** [josepercas/practica_dwec_gestor_presupuesto#3]
@pedroprieto Hola Pedro, estoy teniendo problemas con la práctica "Eventos en JavaScript". Tengo realizada la parte del manejador de eventos "**EditarHandle**" pero no termina de pasar los test. Me da el siguiente error al ejecutar el test **05_testEventos.js**:

![image](https://github.com/josepercas/practica_dwec_gestor_presupuesto/assets/114534674/108a58dd-3b0d-445a-a7ad-bd135c051585)

He intentado resolverlo pero no se por donde seguir. A ver si puedes aclararme un poco donde puedo estar fallando.

Muchas gracias y un saludo.

**Comment by pedroprieto** [comment]
Buenas,

El test espera que pidas el valor antes de la fecha. Simplemente cambia estas dos líneas de orden:
https://github.com/josepercas/practica_dwec_gestor_presupuesto/blob/4fed24a7f9e05134e4d408b57cf73feabc2f0880/js/gestionPresupuestoWeb.js#L219-L220

Me ha costado verlo :sweat_smile: Un saludo!!

**Comment by josepercas** [comment]
@pedroprieto Efectivamente tienes razón!! Ahora si ha pasado el test!! Gracias miles!!  :)
